language: php
php:
  - 5.3
  - 5.4
  - 5.5
notifications:
  irc:
    use_notice: true
    skip_join: true
    channels: ["irc.freenode.org#imbo"]
branches:
  only:
    - develop
    - master
services:
  - mongodb
  - memcached
script: rake travis
