language: php
php:
  - 5.4
  - 5.5
notifications:
  irc:
    use_notice: true
    skip_join: true
    channels: ["irc.freenode.org#imbo"]
branches:
  only:
    - develop
    - master
services:
  - mongodb
  - memcached
before_install:
  - printf "\n" | pecl install imagick-beta
before_script:
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = imagick.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - gem install json
  - composer self-update
  - composer -n --no-ansi install --dev --prefer-source
script: rake test
